baseurl = "https://pottwal.netlify.com/"
languageCode = "en-us"
title = "My New Hugo Site"
theme ="pottwal"

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# All blog posts are defined in their own files.

	name = "pottwal"
	claim = "we have what you want"

  # Navigation
	[params.navigation]
		brand = "brand"

	[params.navigation.links]

  [params.navigation.links.products]
		name     = "products"
		link = "/products"
  [params.navigation.links.collection]
  	name     = "collection"
  	link = "/collection"
	[params.navigation.links.about]
		name     = "about-us"
		link = "/about"
	[params.navigation.links.lookbook]
		name     = "lookbook"
		link = "/lookbook"
	[params.navigation.links.contacts]
		name     = "get in touch"
		link = "/contacts"
